axismundi_web/axismundi_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_portal.urls')),
    path('businesses/', include('businesses.urls')),
    path('invoices/', include('invoices.urls')),
    path('ga-invoices/', include('ga_invoices.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axismundi_web/invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('view/<int:company_id>', views.InvoicesView.as_view(), name='invoices_view'),
    path('analytics-accounts', views.AnalyticsAccountsView.as_view(), name="analytics_accounts"),
    path('analytics-property/<int:account_id>', views.AnalyticsProperties.as_view(),
         name="analytics_properties"),
    path('analytics-views/<str:property_id>', views.AnalyticsViewsView.as_view(), name="analytics_views"),
    path('refresh-analytics-accounts', views.RefreshAccountsView.as_view(), name="refresh_accounts"),
    path('refresh-analytics-properties/<int:account_id>', views.RefreshPropertiesView.as_view(),
         name="refresh_properties"),
    path('refresh-analytics-views/<str:property_id>', views.RefreshViewsView.as_view(),
         name="refresh_views"),
    path('send_invoice_mail', views.InvoiceMailView.as_view(), name='invoice_mail')
]

axismundi_web/invoices/models.py
from django.db import models


class AnalyticsAccount(models.Model):
    account_id = models.CharField(unique=True, max_length=15)
    account_self_link = models.URLField(max_length=200)
    account_name = models.CharField(max_length=100)

    def __str__(self):
        return self.account_name


class AnalyticsProperty(models.Model):
    account = models.ForeignKey(AnalyticsAccount, on_delete=models.CASCADE)
    property_id = models.CharField(unique=True, max_length=15)
    property_self_link = models.URLField(max_length=400)
    property_name = models.CharField(max_length=100)

    def __str__(self):
        return self.property_name


class AnalyticsView(models.Model):
    property = models.ForeignKey(AnalyticsProperty, on_delete=models.CASCADE)
    view_id = models.CharField(unique=True, max_length=15)
    view_self_link = models.URLField(max_length=400)
    view_name = models.CharField(max_length=100)

    def __str__(self):
        return self.view_name


class AnalyticsCompany(models.Model):
    profile = models.OneToOneField(AnalyticsView, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)
    company_site = models.URLField(max_length=100)
    company_saas_url = models.URLField(max_length=100)
    amount_per_session = models.FloatField(default=10.00)
    vat = models.FloatField(default=24.00)

    def __str__(self):
        return self.company_name

axismundi_web/invoices/views.py
import os
import shutil
import calendar

from datetime import datetime
from apiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials

from django.views import View
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.core.files.storage import default_storage

from .src import GoogleAnalyticsData, create_invoice
from .models import *


class IndexView(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = '/admin_panel/login'
    redirect_field_name = "redirect_to"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get(self, request):

        try:
            profiles = get_list_or_404(AnalyticsView)
        except Exception as e:
            profiles = []

        try:
            companies_list = get_list_or_404(AnalyticsCompany)

            invoices_path = os.path.join(settings.MEDIA_ROOT, 'invoices')

            companies = []
            for idx, company in enumerate(companies_list):
                company_path = os.path.join(invoices_path, company.profile.view_id)

                recent_invoice_name = False
                recent_invoice_path = False

                if os.path.exists(company_path):
                    month_folders = os.listdir(company_path)
                    if len(month_folders):
                        recent_month = month_folders[::-1][0]
                        pdf_path = os.path.join(
                            settings.MEDIA_URL, "invoices", str(company.profile.view_id), recent_month, 'invoice.pdf'
                        )

                        month = recent_month.split(" ")
                        month[1] = calendar.month_name[int(month[1])]
                        invoice = " ".join(month[::-1])

                        recent_invoice_name = invoice
                        recent_invoice_path = pdf_path

                companies.append({
                    "id": company.id,
                    "company_site": company.company_site,
                    "company_name": company.company_name,
                    "recent_invoice_name": recent_invoice_name,
                    "recent_invoice_path": recent_invoice_path,
                })
        except Exception as e:
            companies = []

        context = {
            "profiles": profiles,
            "companies": companies
        }

        return render(request, 'invoices/index.html', context)

    def post(self, request):
        profile = AnalyticsView.objects.filter(view_id=request.POST["analytics_id"]).first()

        try:
            company = AnalyticsCompany.objects.get(
                profile=profile
            )
            company.company_name = request.POST["company_name"]
            company.company_site = request.POST["company_site"]
            company.company_saas_url = request.POST["saas_url"]
            company.amount_per_session = request.POST["amount_per_session"]
            company.vat = request.POST["vat"]

        except AnalyticsCompany.DoesNotExist:
            company = AnalyticsCompany(
                profile=profile,
                company_name=request.POST["company_name"],
                company_site=request.POST["company_site"],
                company_saas_url=request.POST["saas_url"],
                amount_per_session=request.POST["amount_per_session"],
                vat=request.POST["vat"]
            )

        company.save()

        return redirect('invoices:index')


class InvoicesView(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = '/admin_panel/login'
    redirect_field_name = "redirect_to"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get(self, request, company_id=None):

        company = AnalyticsCompany.objects.filter(id=company_id).first()

        invoices_path = os.path.join(settings.MEDIA_ROOT, 'invoices')
        if not os.path.exists(invoices_path):
            os.makedirs(invoices_path)

        company_path = os.path.join(invoices_path, company.profile.view_id)
        if not os.path.exists(company_path):
            os.makedirs(company_path)

        month_folders = os.listdir(company_path)
        month_folders = month_folders[::-1]
        invoices = []
        if len(month_folders):
            for ix, month in enumerate(month_folders):
                pdf_path = os.path.join(settings.MEDIA_URL, "invoices", str(company.profile.view_id), month_folders[ix], 'invoice.pdf')

                month = month.split(" ")
                month[1] = calendar.month_name[int(month[1])]
                invoice = " ".join(month[::-1])
                invoices.append({
                        "name": invoice,
                        "path": pdf_path
                    })

        context = {
            "company": company,
            "invoices": invoices
        }

        return render(request, 'invoices/invoices.html', context)

    def post(self, request, company_id=None):
        company = AnalyticsCompany.objects.filter(id=company_id).first()
        profile_id = company.profile.view_id

        # check for invoices folder
        invoices_path = os.path.join(settings.MEDIA_ROOT, 'invoices')
        if not os.path.exists(invoices_path):
            os.makedirs(invoices_path)

        # check company folder under invoices folder
        company_path = os.path.join(invoices_path, company.profile.view_id)
        if not os.path.exists(company_path):
            os.makedirs(company_path)

        # collect date range
        month_num = int(request.POST["month"])
        year = int(request.POST["year"])
        last_date = calendar.monthrange(year, month_num)[1]

        # make the starting and ending date
        start_date = datetime.strptime(f"1-{month_num}-{year}", '%d-%m-%Y').strftime('%Y-%m-%d')
        end_date = datetime.strptime(f"{last_date}-{month_num}-{year}", '%d-%m-%Y').strftime('%Y-%m-%d')

        # check for month folder
        month_folder = os.path.join(company_path, f"{year} {month_num}")
        if not os.path.exists(month_folder):
            os.makedirs(month_folder)

        # collect data from google analytics
        analytics_data = GoogleAnalyticsData(
            view_id=profile_id,
            start_date=start_date,
            end_date=end_date,
            storage_path=month_folder
        ).collect()

        create_invoice(analytics_data, company, month_folder, month_num, year)

        return redirect('invoices:invoices_view', company.id)


class AnalyticsAccountsView(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = '/admin_panel/login'
    redirect_field_name = "redirect_to"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get(self, request):

        try:
            accounts = get_list_or_404(AnalyticsAccount)
        except Exception as e:
            print("Error in collecting Analytics Accounts details,", e)
            accounts = []

        context = {
            "accounts": accounts
        }

        return render(request, 'invoices/accounts.html', context=context)


class RefreshAccountsView(View):

    def get(self, request):
        scopes = [os.getenv("ANALYTICS_SCOPE")]
        key_file_location = 'client_secrets.json'
        api_name = 'analytics',
        api_version = 'v3',

        # Get a service that communicates to a Google API
        credentials = ServiceAccountCredentials.from_json_keyfile_name(key_file_location, scopes=scopes)
        # Build the service object.
        service = build(api_name, api_version, credentials=credentials)

        # Get a list of all Google Analytics accounts for this user
        accounts = service.management().accounts().list().execute()

        for account in accounts.get("items"):
            if account:
                try:
                    account_db = AnalyticsAccount.objects.get(
                        account_id=account.get('id')
                    )
                except AnalyticsAccount.DoesNotExist:
                    account_db = AnalyticsAccount(
                        account_id=account.get('id'),
                        account_self_link=account.get('selfLink'),
                        account_name=account.get('name'),
                    )
                # else:
                #     account_db.account_self_link = account.get('selfLink')
                #     account_db.account_name = account.get('name')

                account_db.save()

        return redirect('invoices:analytics_accounts')


class AnalyticsProperties(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = '/admin_panel/login'
    redirect_field_name = "redirect_to"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get(self, request, account_id=None):
        if account_id is None:
            return redirect('invoices:analytics_accounts')

        account = AnalyticsAccount.objects.filter(account_id=account_id).first()

        try:
            properties = get_list_or_404(AnalyticsProperty, account_id=account)
        except Exception as e:
            print("Error in collecting Analytics Accounts details,", e)
            properties = []

        context = {
            "account": account,
            "properties": properties
        }

        return render(request, 'invoices/properties.html', context=context)


class RefreshPropertiesView(View):

    def get(self, request, account_id=None):
        if account_id is None:
            return redirect('invoices:analytics_accounts')

        scopes = [os.getenv("ANALYTICS_SCOPE")]

axismundi_web/invoices/templates/invoices/accounts.html
{% extends "admin_portal/base.html" %}
{% load static %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Google Analytics,</h2>
        <p class="mb-md-0">Accounts.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Analytics&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;Accounts</p>
      </div>
    </div>
      <div class="d-flex justify-content-between align-items-end flex-wrap">
          <a href="{% url 'invoices:refresh_accounts' %}">
              <button class="btn btn-primary mt-2 mt-xl-0">Refresh Account</button>
          </a>
      </div>
  </div>
</div>
</div>

<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Accounts</h4>
        <p class="card-description">
          List of Registered Google Analytics Accounts
        </p>
        <div class="table-responsive pt-3">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
              {% for account in accounts %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ account.account_id }}</td>
                <td><a href="{% url 'invoices:analytics_properties' account.account_id %}">{{ account.account_name }}</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}



axismundi_web/invoices/templates/invoices/index.html
{% extends "admin_portal/base.html" %}
{% load static %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Invoices,</h2>
        <p class="mb-md-0">SaaS Invoices.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Dashboard&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;Invoices</p>
      </div>
    </div>
  </div>
</div>
</div>

<div class="row">
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add New Company</h4>
            <form class="forms-sample" action="{% url 'invoices:index' %}" method="post">
              {% csrf_token %}
              <div class="col-md-4 form-group float-left">
                <label for="company_name">Company Name</label>
                <input type="text" class="form-control form-control-sm" id="company_name" name="company_name" value="" required>
              </div>
              <div class="col-md-4 form-group float-left">
                <label for="company_site">Company Site</label>
                <input type="text" class="form-control form-control-sm" id="company_site" name="company_site" value="" required>
              </div>
              <div class="col-md-4 form-group float-left">
                <label for="saas_url">SaaS URL</label>
                <input type="text" class="form-control form-control-sm" id="saas_url" name="saas_url" value="">
              </div>
              <div class="col-md-7 form-group float-left">
                <label for="analytics_id">Analytics ID</label>
                <select class="form-control form-control-sm" id="analytics_id" name="analytics_id" required>
                  {% for profile in profiles %}
                    <option value="{{profile.view_id}}">
                      {{profile.property.account.account_name}} >
                      {{profile.property.property_name}} >
                      {{profile.view_name}} ({{profile.view_id}})
                    </option>
                  {% endfor %}
                </select>

              </div>
              <div class="col-md-3 form-group float-left">
                <label for="amount_per_session">Per Session Amount (EURO)</label>
                <input type="hidden" name="amount_per_session" value="25.00">
                <input type="number" step="0.01" class="form-control form-control-sm" id="amount_per_session" disabled value="25.00" min="25.00" required>
              </div>
              <div class="col-md-2 form-group float-left">
                <label for="vat">VAT (%)</label>
                <input type="hidden" name="vat" value="24.00">
                <input type="number" step="0.01" class="form-control form-control-sm" id="vat" disabled value="24.00" min="24.00" required>
              </div>


                <div class="col-md-3 form-group float-left">
                    <button type="submit" class="btn btn-primary mt-4">Add Company</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

<div class="row">
<div class="col-md-12 stretch-card">
  <div class="card">
    <div class="card-body">
      <p class="card-title">Companies</p>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Invoices</th>
            </tr>
          </thead>
          <tbody>
            {% for company in companies %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>
                    <a href="{{company.company_site}}" target="_blank">{{company.company_name}}</a>
                  </td>
                  <td>
                    {% if company.recent_invoice_name %}
                    <a href="{{company.recent_invoice_path}}" target="_blank">
                      <button class="btn btn-primary">Download ({{company.recent_invoice_name}})</button>
                    </a>
                    <button class="btn btn-primary" id="send_mail" value="{{company.id}}">Send Mail ({{company.recent_invoice_name}})</button>
                    {% else %}
                      <button class="btn btn-primary" disabled>No Invoices Available</button>
                    {% endif %}

                    <a href="{% url 'invoices:invoices_view' company.id %}">
                      <button class="btn btn-primary">View Invoices</button>
                    </a>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>





<script>
    $("#send_mail").click(function () {
      $("#spin_loader").css("visibility", "visible");
      $("html").css("overflow", "hidden");

      var company_id = $(this).attr('value');
      var token = '{{csrf_token}}'

      $.ajax({
        type: "POST",
        headers: { "X-CSRFToken": token },
        url: '/invoices/send_invoice_mail',
        data: {
          'company_id': company_id,
        },
        dataType: 'json',
        success: function (data) {
          if (!data.res) {
            alert("error in sending mail!");
          }else {
            alert("mail sent!")
          }
          $("#spin_loader").css("visibility", "hidden");
          $("html").css("overflow", "scroll");
        }
      });

    });
</script>


{% endblock %}






axismundi_web/invoices/templates/invoices/invoices.html
{% extends "admin_portal/base.html" %}
{% load static %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Invoices,</h2>
        <p class="mb-md-0">SaaS Invoices.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Dashboard&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;Invoices</p>
      </div>
    </div>
  </div>
</div>
</div>

<div class="row">
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add New Company</h4>
            <form class="forms-sample" action="{% url 'invoices:invoices_view' company.id %}" method="post">
              {% csrf_token %}
              <div class="col-md-4 form-group float-left">
                <label for="month">Month</label>
                <select class="form-control form-control-sm" id="month" name="month" required>
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
              </div>
              <div class="col-md-4 form-group float-left">
                <label for="year">Year</label>
                <select class="form-control form-control-sm" id="year" name="year" required>
                    <option value="2021">2021</option>
                    <option value="2020">2020</option>
                    <option value="2019">2019</option>
                </select>
              </div>
                <div class="col-md-3 form-group float-left">
                    <button type="submit" class="btn btn-primary mt-4">Generate</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

<div class="row">
    {% for invoice in invoices %}
        <div class="col-lg-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">{{invoice.name}}</h4>
                <div class="col-md-12" style="float:left">
                    <a href="{{invoice.path}}" target="_blank">
                        <h5 class="col-md-5" style="float:left;margin-top:30px">Invoice</h5>
                        <div class="col-md-7" style="float:left">
                            <img src="{% static 'admin_portal/images/icons/pdf-icon.png' %}" style="width:80px;height:80px;float:left"/>
                        </div>
                    </a>
                </div>
<!--                <div class="col-md-12" style="margin-top:15px;float:left">-->
<!--                    <a href="#" target="_blank">-->
<!--                        <h5 class="col-md-5" style="float:left;margin-top:30px">Lasku</h5>-->
<!--                        <div class="col-md-7" style="float:left">-->
<!--                            <img src="{% static 'admin_portal/images/icons/pdf-icon.png' %}" style="width:80px;height:80px;float:left"/>-->
<!--                        </div>-->
<!--                    </a>-->
<!--                </div>-->
            </div>
          </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

axismundi_web/invoices/templates/invoices/properties.html
{% extends "admin_portal/base.html" %}
{% load static %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Google Analytics,</h2>
        <p class="mb-md-0">Properties.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Analytics&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;<a href="{% url 'invoices:analytics_accounts' %}">Account</a>&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;Properties</p>
      </div>
    </div>
      <div class="d-flex justify-content-between align-items-end flex-wrap">
          <a href="{% url 'invoices:refresh_properties' account.account_id %}">
              <button class="btn btn-primary mt-2 mt-xl-0">Refresh Properties</button>
          </a>
      </div>
  </div>
</div>
</div>

<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Analytics Properties</h4>
        <p class="card-description">
          List of Registered Properties in Analytics Account - <code>{{ account }}</code>
        </p>
        <div class="table-responsive pt-3">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
              {% for property in properties %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ property.property_id }}</td>
                <td><a href="{% url 'invoices:analytics_views' property.property_id %}">{{ property.property_name }}</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}



axismundi_web/invoices/templates/invoices/views.html
{% extends "admin_portal/base.html" %}
{% load static %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Google Analytics,</h2>
        <p class="mb-md-0">Views.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Analytics&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;<a href="{% url 'invoices:analytics_accounts' %}">Account</a>&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;<a href="{% url 'invoices:analytics_properties' property.account.account_id %}">Property</a>&nbsp;</p>
        <p class="text-primary mb-0 hover-cursor">/&nbsp;Views</p>
      </div>
    </div>
      <div class="d-flex justify-content-between align-items-end flex-wrap">
          <a href="{% url 'invoices:refresh_views' property.property_id %}">
              <button class="btn btn-primary mt-2 mt-xl-0">Refresh Views</button>
          </a>
      </div>
  </div>
</div>
</div>

<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Analytics Properties</h4>
        <p class="card-description">
          List of Registered Properties in Analytics Account - <code>{{ account }}</code> > <code>{{ property }}</code>
        </p>
        <div class="table-responsive pt-3">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
              {% for view in views %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ view.view_id }}</td>
                <td>{{ view.view_name }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

