axismundi_web/admin_portal/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'admin_portal'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin_panel/login', views.LoginView.as_view(), name="admin_login"),
    path('admin_panel/logout', views.LogOutView.as_view(), name="admin_logout")
]

axismundi_web/axismundi_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_portal.urls')),
    path('businesses/', include('businesses.urls')),
    path('invoices/', include('invoices.urls')),
    path('ga-invoices/', include('ga_invoices.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

axismundi_web/businesses/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'businesses'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('businesses_excel', views.BusinessesExcelView.as_view(), name='businesses_excel'),
    path('businesses_load', views.BusinessesLoadView.as_view(), name='load_businesses'),
    path('celery', views.CeleryView.as_view(), name='celery')
]

axismundi_web/ga_invoices/urls.py
from django.urls import path

from . import views

app_name = 'ga_invoices'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('accounts', views.AccountView.as_view(), name='company_register'),
]

axismundi_web/invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('view/<int:company_id>', views.InvoicesView.as_view(), name='invoices_view'),
    path('analytics-accounts', views.AnalyticsAccountsView.as_view(), name="analytics_accounts"),
    path('analytics-property/<int:account_id>', views.AnalyticsProperties.as_view(),
         name="analytics_properties"),
    path('analytics-views/<str:property_id>', views.AnalyticsViewsView.as_view(), name="analytics_views"),
    path('refresh-analytics-accounts', views.RefreshAccountsView.as_view(), name="refresh_accounts"),
    path('refresh-analytics-properties/<int:account_id>', views.RefreshPropertiesView.as_view(),
         name="refresh_properties"),
    path('refresh-analytics-views/<str:property_id>', views.RefreshViewsView.as_view(),
         name="refresh_views"),
    path('send_invoice_mail', views.InvoiceMailView.as_view(), name='invoice_mail')
]

axismundi_web/admin_portal/models.py
from django.db import models

# Create your models here.

axismundi_web/admin_portal/views.py
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404


from .models import *


class IndexView(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = '/admin_panel/login'
    redirect_field_name = "redirect_to"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get(self, request):

        return render(request, 'admin_portal/index.html')


class LoginView(View):

    def get(self, request):

        if request.user.is_authenticated:
            return redirect('admin_portal:index')

        return render(request, 'admin_portal/login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        context = {}
        if user is not None:
            login(request, user)
            return redirect("admin_portal:index")
        else:
            context["error"] = "Invalid Admin Credentials"

        return render(request, 'admin_portal/login.html', context)


class LogOutView(View):

    def get(self, request):
        logout(request)
        return redirect('admin_portal:admin_login')

axismundi_web/admin_portal/templates/admin_portal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Axis Mundi</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'admin_portal/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'admin_portal/vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="{% static 'admin_portal/vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'admin_portal/css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'admin_portal/images/favicon.png' %}" />
  <script src="{% static 'admin_portal/js/jquery.min.js' %}"></script>
  <style>
    .loader {
      border: 16px solid #f3f3f3; /* Light grey */
      border-top: 16px solid #3498db; /* Blue */
      border-radius: 50%;
      width: 120px;
      height: 120px;
      position: absolute;
      top: 50%;
      left: 50%;
      animation: spin 2s linear infinite;
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  </style>
</head>
<body>
  <div style="width:100%;height:100vh;position:absolute;z-index:10000;background:rgba(0, 0, 0, 0.5);visibility:hidden;" id="spin_loader">
    <div class="loader"></div>
  </div>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
          <a class="navbar-brand brand-logo" href="{% url 'admin_portal:index' %}"></a>
          <a class="navbar-brand brand-logo-mini" href="{% url 'admin_portal:index' %}"></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search" disabled>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown mr-1">
            <!-- Message Icon -->
          </li>
          <li class="nav-item dropdown mr-4">
            <!-- Notification Icon -->
          </li>
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="{% static 'admin_portal/images/icons/logo.jpeg' %}" alt="profile"/>
              <span class="nav-profile-name">Admin</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Settings
              </a>
              <a class="dropdown-item" href="{% url 'admin_portal:admin_logout' %}">
                <i class="mdi mdi-logout text-primary"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item {% if request.path == '/' %} active {% endif %}">
            <a class="nav-link" href="{% url 'admin_portal:index' %}">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item {% if 'businesses' in request.path %} active {% endif %}">
            <a class="nav-link" href="{% url 'businesses:index' %}">
              <i class="mdi mdi-view-headline menu-icon"></i>
              <span class="menu-title">Businesses</span>
            </a>
          </li>
          <li class="nav-item {% if 'invoices' in request.path %} active {% endif %}">
            <a class="nav-link" href="{% url 'ga_invoices:index' %}">
              <i class="mdi mdi-circle-outline menu-icon"></i>
              <span class="menu-title">Invoices History</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
        {% block content %}
        {% endblock %}
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © axis_mundi 2020</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Axis Mundi</span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static 'admin_portal/vendors/base/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="{% static 'admin_portal/vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'admin_portal/vendors/datatables.net/jquery.dataTables.js' %}"></script>
  <script src="{% static 'admin_portal/vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static 'admin_portal/js/off-canvas.js' %}"></script>
  <script src="{% static 'admin_portal/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'admin_portal/js/template.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'admin_portal/js/dashboard.js' %}"></script>
  <script src="{% static 'admin_portal/js/data-table.js' %}"></script>
  <script src="{% static 'admin_portal/js/jquery.dataTables.js' %}"></script>
  <script src="{% static 'admin_portal/js/dataTables.bootstrap4.js' %}"></script>
  <!-- End custom js for this page-->
  <script src="{% static 'admin_portal/js/jquery.cookie.js' %}" type="text/javascript"></script>
</body>

</html>


axismundi_web/admin_portal/templates/admin_portal/index.html
{% extends "admin_portal/base.html" %}

{% block content %}
<div class="row">
<div class="col-md-12 grid-margin">
  <div class="d-flex justify-content-between flex-wrap">
    <div class="d-flex align-items-end flex-wrap">
      <div class="mr-md-3 mr-xl-5">
        <h2>Welcome back,</h2>
        <p class="mb-md-0">Axis Mundi Admin Portal.</p>
      </div>
      <div class="d-flex">
        <i class="mdi mdi-home text-muted hover-cursor"></i>
        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Dashboard&nbsp;</p>
<!--        <p class="text-primary mb-0 hover-cursor">/&nbsp;Analytics</p>-->
      </div>
    </div>
  </div>
</div>
</div>

<div class="row">
<div class="col-md-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body dashboard-tabs p-0">
      <ul class="nav nav-tabs px-4" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Overview</a>
        </li>
      </ul>
      <div class="tab-content py-0 px-0">
        <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
          <div class="d-flex flex-wrap justify-content-xl-between">
            <div class="d-none d-xl-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item">
              <i class="mdi mdi-calendar-heart icon-lg mr-3 text-primary"></i>
              <div class="d-flex flex-column justify-content-around">
                <small class="mb-1 text-muted">Latest update</small>
                <h5 class="mb-0 d-inline-block">26 Jul 2018</h5>
              </div>
            </div>
            <div class="d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item">
              <i class="mdi mdi-eye mr-3 icon-lg text-success"></i>
              <div class="d-flex flex-column justify-content-around">
                <small class="mb-1 text-muted"># of Businesses</small>
                <h5 class="mr-2 mb-0">$577545</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

axismundi_web/admin_portal/templates/admin_portal/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Axis Mundi</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'admin_portal/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'admin_portal/vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'admin_portal/css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'admin_portal/images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="{% static 'admin_portal/images/icons/logo.jpeg' %}" style="margin-left:30%" alt="logo">
              </div>
<!--              <h4>Hello! let's get started</h4>-->
<!--              <h6 class="font-weight-light">Sign in to continue.</h6>-->
              <form class="pt-3" method="post" action="{% url 'admin_portal:admin_login' %}">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control form-control-lg" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control form-control-lg" name="password" placeholder="Password">
                </div>
                <div class="mt-3">
                  <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">SIGN IN</button>
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                      <p style="color:red">{{error}}</p>
                  </div>

                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'admin_portal/vendors/base/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'admin_portal/js/off-canvas.js' %}"></script>
  <script src="{% static 'admin_portal/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'admin_portal/js/template.js' %}"></script>
  <!-- endinject -->
</body>

</html>